name: Build and Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Version tag (e.g., v1.0.0)
        required: true

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Build with ncc
        run: npm run build
      - name: Zip build artifacts
        run: zip -r build-${{ github.event.inputs.tag }}.zip index.js
      - name: Create tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          rm -rf src
          git add -f index.js
          git add -u
          git commit -m "Build for release ${{ github.event.inputs.tag }}"
          git tag ${{ github.event.inputs.tag }}
          git push origin ${{ github.event.inputs.tag }}
      - name: Create GitHub release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag }}
          generate_release_notes: true
