name: Test Get Supported GHC Version Action

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v7
      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: '24'
      - name: Install dependencies
        run: npm clean-install
      - name: Check formatting with js-beautify
        run: |
          npm run format
          git diff --exit-code
        shell: bash
      - run: npm test
