name: Test Get Supported GHC Version Action

on:
  push:
    branches: [master]
  pull_request:

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - run: npm install
      - name: Check formatting with js-beautify
        run: |
          npx js-beautify -r -n "**/*.js"
          npx js-beautify -r -n "package.json"
          git diff --exit-code
      - run: npm run build
      - name: Run action with inclusive upper bound
        uses: ./
        with:
          package-yaml-path: examples/package-equal-or-less-than.yaml
        id: ghc-version-inclusive
      - name: Assert output
        run: |-
          if [ "${{ steps.ghc-version-inclusive.outputs.ghc-version }}" != "9.0.1" ]; then
            exit 1
          fi
      - name: Run action with exclusive upper bound
        uses: ./
        with:
          package-yaml-path: examples/package-less-than.yaml
        id: ghc-version-exclusive
      - name: Assert output
        run: |-
          if [ "${{ steps.ghc-version-exclusive.outputs.ghc-version }}" != "8.10.7" ]; then
            exit 1
          fi
